package models

/**
  * Created by michael on 17/12/16.
  */


case class Note private(pitchClass: String, name: String, keyNum: Int)

object Note {

  val A0: Note = Note("A", "A0", 1)
  val As0: Note = Note("A♯", "A♯0", 2)
  val Bb0: Note = Note("B♭", "B♭0", 2)
  val B0: Note = Note("B", "B0", 3)

  val C1: Note = Note("C", "C1", 4)
  val Cs1: Note = Note("C♯", "C♯1", 5)
  val Db1: Note = Note("D♭", "D♭1", 5)
  val D1: Note = Note("D", "D1", 6)
  val Ds1: Note = Note("D♯", "D♯1", 7)
  val Eb1: Note = Note("E♭", "E♭1", 7)
  val E1: Note = Note("E", "E1", 8)
  val F1: Note = Note("F", "F1", 9)
  val Fs1: Note = Note("F♯", "F♯1", 10)
  val Gb1: Note = Note("G♭", "G♭1", 10)
  val G1: Note = Note("G", "G1", 11)
  val Gs1: Note = Note("G♯", "G♯1", 12)
  val Ab1: Note = Note("A♭", "A♭1", 12)
  val A1: Note = Note("A", "A1", 13)
  val As1: Note = Note("A♯", "A♯1", 14)
  val Bb1: Note = Note("B♭", "B♭1", 14)
  val B1: Note = Note("B", "B1", 15)

  val C2: Note = Note("C", "C2", 16)
  val Cs2: Note = Note("C♯", "C♯2", 17)
  val Db2: Note = Note("D♭", "D♭2", 17)
  val D2: Note = Note("D", "D2", 18)
  val Ds2: Note = Note("D♯", "D♯2", 19)
  val Eb2: Note = Note("E♭", "E♭2", 19)
  val E2: Note = Note("E", "E2", 20)
  val F2: Note = Note("F", "F2", 21)
  val Fs2: Note = Note("F♯", "F♯2", 22)
  val Gb2: Note = Note("G♭", "G♭2", 22)
  val G2: Note = Note("G", "G2", 23)
  val Gs2: Note = Note("G♯", "G♯2", 24)
  val Ab2: Note = Note("A♭", "A♭2", 24)
  val A2: Note = Note("A", "A2", 25)
  val As2: Note = Note("A♯", "A♯2", 26)
  val Bb2: Note = Note("B♭", "B♭2", 26)
  val B2: Note = Note("B", "B2", 27)

  val C3:  Note = Note("C", "C3", 28)
  val Cs3: Note = Note("C♯", "C♯3", 29)
  val Db3: Note = Note("D♭", "D♭3", 29)
  val D3:  Note = Note("D", "D3", 30)
  val Ds3: Note = Note("D♯", "D♯3", 31)
  val Eb3: Note = Note("E♭", "E♭3", 31)
  val E3:  Note = Note("E", "E3", 32)
  val F3:  Note = Note("F", "F3", 33)
  val Fs3: Note = Note("F♯", "F♯3", 34)
  val Gb3: Note = Note("G♭", "G♭3", 34)
  val G3:  Note = Note("G", "G3", 35)
  val Gs3: Note = Note("G♯", "G♯3", 36)
  val Ab3: Note = Note("A♭", "A♭3", 36)
  val A3:  Note = Note("A", "A3", 37)
  val As3: Note = Note("A♯", "A♯3", 38)
  val Bb3: Note = Note("B♭", "B♭3", 38)
  val B3:  Note = Note("B", "B3", 39)

  val C4:  Note = Note("C", "C4", 40)
  val Cs4: Note = Note("C♯", "C♯4", 41)
  val Db4: Note = Note("D♭", "D♭4", 41)
  val D4:  Note = Note("D", "D4", 42)
  val Ds4: Note = Note("D♯", "D♯4", 43)
  val Eb4: Note = Note("E♭", "E♭4", 43)
  val E4:  Note = Note("E", "E4", 44)
  val F4:  Note = Note("F", "F4", 45)
  val Fs4: Note = Note("F♯", "F♯4", 46)
  val Gb4: Note = Note("G♭", "G♭4", 46)
  val G4:  Note = Note("G", "G4", 47)
  val Gs4: Note = Note("G♯", "G♯4", 48)
  val Ab4: Note = Note("A♭", "A♭4", 48)
  val A4:  Note = Note("A", "A4", 49)
  val As4: Note = Note("A♯", "A♯4", 50)
  val Bb4: Note = Note("B♭", "B♭4", 50)
  val B4:  Note = Note("B", "B4", 51)

  val C5:  Note = Note("C", "C5", 52)
  val Cs5: Note = Note("C♯", "C♯5", 53)
  val Db5: Note = Note("D♭", "D♭5", 53)
  val D5:  Note = Note("D", "D5", 54)
  val Ds5: Note = Note("D♯", "D♯5", 55)
  val Eb5: Note = Note("E♭", "E♭5", 55)
  val E5:  Note = Note("E", "E5", 56)
  val F5:  Note = Note("F", "F5", 57)
  val Fs5: Note = Note("F♯", "F♯5", 58)
  val Gb5: Note = Note("G♭", "G♭5", 58)
  val G5:  Note = Note("G", "G5", 59)
  val Gs5: Note = Note("G♯", "G♯5", 60)
  val Ab5: Note = Note("A♭", "A♭5", 60)
  val A5:  Note = Note("A", "A5", 61)
  val As5: Note = Note("A♯", "A♯5", 62)
  val Bb5: Note = Note("B♭", "B♭5", 62)
  val B5:  Note = Note("B", "B5", 63)

  val C6:  Note = Note("C", "C6", 64)
  val Cs6: Note = Note("C♯", "C♯6", 65)
  val Db6: Note = Note("D♭", "D♭6", 65)
  val D6:  Note = Note("D", "D6", 66)
  val Ds6: Note = Note("D♯", "D♯6", 67)
  val Eb6: Note = Note("E♭", "E♭6", 67)
  val E6:  Note = Note("E", "E6", 68)
  val F6:  Note = Note("F", "F6", 69)
  val Fs6: Note = Note("F♯", "F♯6", 70)
  val Gb6: Note = Note("G♭", "G♭6", 70)
  val G6:  Note = Note("G", "G6", 71)
  val Gs6: Note = Note("G♯", "G♯6", 72)
  val Ab6: Note = Note("A♭", "A♭6", 72)
  val A6:  Note = Note("A", "A6", 73)
  val As6: Note = Note("A♯", "A♯6", 74)
  val Bb6: Note = Note("B♭", "B♭6", 74)
  val B6:  Note = Note("B", "B6", 75)

  val C7:  Note = Note("C", "C7", 76)
  val Cs7: Note = Note("C♯", "C♯7", 77)
  val Db7: Note = Note("D♭", "D♭7", 77)
  val D7:  Note = Note("D", "D7", 78)
  val Ds7: Note = Note("D♯", "D♯7", 79)
  val Eb7: Note = Note("E♭", "E♭7", 79)
  val E7:  Note = Note("E", "E7", 80)
  val F7:  Note = Note("F", "F7", 81)
  val Fs7: Note = Note("F♯", "F♯7", 82)
  val Gb7: Note = Note("G♭", "G♭7", 82)
  val G7:  Note = Note("G", "G7", 83)
  val Gs7: Note = Note("G♯", "G♯7", 84)
  val Ab7: Note = Note("A♭", "A♭7", 84)
  val A7:  Note = Note("A", "A7", 85)
  val As7: Note = Note("A♯", "A♯7", 86)
  val Bb7: Note = Note("B♭", "B♭7", 86)
  val B7:  Note = Note("B", "B7", 87)

  val C8:  Note = Note("C", "C8", 88)
}

