package models

/**
  * Created by michael on 17/12/16.
  */


case class oldNote private(pitchClass: String, name: String, keyNum: Int)

object oldNote {

  val A0: oldNote = oldNote("A", "A0", 1)
  val As0: oldNote = oldNote("A♯", "A♯0", 2)
  val Bb0: oldNote = oldNote("B♭", "B♭0", 2)
  val B0: oldNote = oldNote("B", "B0", 3)

  val C1: oldNote = oldNote("C", "C1", 4)
  val Cs1: oldNote = oldNote("C♯", "C♯1", 5)
  val Db1: oldNote = oldNote("D♭", "D♭1", 5)
  val D1: oldNote = oldNote("D", "D1", 6)
  val Ds1: oldNote = oldNote("D♯", "D♯1", 7)
  val Eb1: oldNote = oldNote("E♭", "E♭1", 7)
  val E1: oldNote = oldNote("E", "E1", 8)
  val F1: oldNote = oldNote("F", "F1", 9)
  val Fs1: oldNote = oldNote("F♯", "F♯1", 10)
  val Gb1: oldNote = oldNote("G♭", "G♭1", 10)
  val G1: oldNote = oldNote("G", "G1", 11)
  val Gs1: oldNote = oldNote("G♯", "G♯1", 12)
  val Ab1: oldNote = oldNote("A♭", "A♭1", 12)
  val A1: oldNote = oldNote("A", "A1", 13)
  val As1: oldNote = oldNote("A♯", "A♯1", 14)
  val Bb1: oldNote = oldNote("B♭", "B♭1", 14)
  val B1: oldNote = oldNote("B", "B1", 15)

  val C2: oldNote = oldNote("C", "C2", 16)
  val Cs2: oldNote = oldNote("C♯", "C♯2", 17)
  val Db2: oldNote = oldNote("D♭", "D♭2", 17)
  val D2: oldNote = oldNote("D", "D2", 18)
  val Ds2: oldNote = oldNote("D♯", "D♯2", 19)
  val Eb2: oldNote = oldNote("E♭", "E♭2", 19)
  val E2: oldNote = oldNote("E", "E2", 20)
  val F2: oldNote = oldNote("F", "F2", 21)
  val Fs2: oldNote = oldNote("F♯", "F♯2", 22)
  val Gb2: oldNote = oldNote("G♭", "G♭2", 22)
  val G2: oldNote = oldNote("G", "G2", 23)
  val Gs2: oldNote = oldNote("G♯", "G♯2", 24)
  val Ab2: oldNote = oldNote("A♭", "A♭2", 24)
  val A2: oldNote = oldNote("A", "A2", 25)
  val As2: oldNote = oldNote("A♯", "A♯2", 26)
  val Bb2: oldNote = oldNote("B♭", "B♭2", 26)
  val B2: oldNote = oldNote("B", "B2", 27)

  val C3:  oldNote = oldNote("C", "C3", 28)
  val Cs3: oldNote = oldNote("C♯", "C♯3", 29)
  val Db3: oldNote = oldNote("D♭", "D♭3", 29)
  val D3:  oldNote = oldNote("D", "D3", 30)
  val Ds3: oldNote = oldNote("D♯", "D♯3", 31)
  val Eb3: oldNote = oldNote("E♭", "E♭3", 31)
  val E3:  oldNote = oldNote("E", "E3", 32)
  val F3:  oldNote = oldNote("F", "F3", 33)
  val Fs3: oldNote = oldNote("F♯", "F♯3", 34)
  val Gb3: oldNote = oldNote("G♭", "G♭3", 34)
  val G3:  oldNote = oldNote("G", "G3", 35)
  val Gs3: oldNote = oldNote("G♯", "G♯3", 36)
  val Ab3: oldNote = oldNote("A♭", "A♭3", 36)
  val A3:  oldNote = oldNote("A", "A3", 37)
  val As3: oldNote = oldNote("A♯", "A♯3", 38)
  val Bb3: oldNote = oldNote("B♭", "B♭3", 38)
  val B3:  oldNote = oldNote("B", "B3", 39)

  val C4:  oldNote = oldNote("C", "C4", 40)
  val Cs4: oldNote = oldNote("C♯", "C♯4", 41)
  val Db4: oldNote = oldNote("D♭", "D♭4", 41)
  val D4:  oldNote = oldNote("D", "D4", 42)
  val Ds4: oldNote = oldNote("D♯", "D♯4", 43)
  val Eb4: oldNote = oldNote("E♭", "E♭4", 43)
  val E4:  oldNote = oldNote("E", "E4", 44)
  val F4:  oldNote = oldNote("F", "F4", 45)
  val Fs4: oldNote = oldNote("F♯", "F♯4", 46)
  val Gb4: oldNote = oldNote("G♭", "G♭4", 46)
  val G4:  oldNote = oldNote("G", "G4", 47)
  val Gs4: oldNote = oldNote("G♯", "G♯4", 48)
  val Ab4: oldNote = oldNote("A♭", "A♭4", 48)
  val A4:  oldNote = oldNote("A", "A4", 49)
  val As4: oldNote = oldNote("A♯", "A♯4", 50)
  val Bb4: oldNote = oldNote("B♭", "B♭4", 50)
  val B4:  oldNote = oldNote("B", "B4", 51)

  val C5:  oldNote = oldNote("C", "C5", 52)
  val Cs5: oldNote = oldNote("C♯", "C♯5", 53)
  val Db5: oldNote = oldNote("D♭", "D♭5", 53)
  val D5:  oldNote = oldNote("D", "D5", 54)
  val Ds5: oldNote = oldNote("D♯", "D♯5", 55)
  val Eb5: oldNote = oldNote("E♭", "E♭5", 55)
  val E5:  oldNote = oldNote("E", "E5", 56)
  val F5:  oldNote = oldNote("F", "F5", 57)
  val Fs5: oldNote = oldNote("F♯", "F♯5", 58)
  val Gb5: oldNote = oldNote("G♭", "G♭5", 58)
  val G5:  oldNote = oldNote("G", "G5", 59)
  val Gs5: oldNote = oldNote("G♯", "G♯5", 60)
  val Ab5: oldNote = oldNote("A♭", "A♭5", 60)
  val A5:  oldNote = oldNote("A", "A5", 61)
  val As5: oldNote = oldNote("A♯", "A♯5", 62)
  val Bb5: oldNote = oldNote("B♭", "B♭5", 62)
  val B5:  oldNote = oldNote("B", "B5", 63)

  val C6:  oldNote = oldNote("C", "C6", 64)
  val Cs6: oldNote = oldNote("C♯", "C♯6", 65)
  val Db6: oldNote = oldNote("D♭", "D♭6", 65)
  val D6:  oldNote = oldNote("D", "D6", 66)
  val Ds6: oldNote = oldNote("D♯", "D♯6", 67)
  val Eb6: oldNote = oldNote("E♭", "E♭6", 67)
  val E6:  oldNote = oldNote("E", "E6", 68)
  val F6:  oldNote = oldNote("F", "F6", 69)
  val Fs6: oldNote = oldNote("F♯", "F♯6", 70)
  val Gb6: oldNote = oldNote("G♭", "G♭6", 70)
  val G6:  oldNote = oldNote("G", "G6", 71)
  val Gs6: oldNote = oldNote("G♯", "G♯6", 72)
  val Ab6: oldNote = oldNote("A♭", "A♭6", 72)
  val A6:  oldNote = oldNote("A", "A6", 73)
  val As6: oldNote = oldNote("A♯", "A♯6", 74)
  val Bb6: oldNote = oldNote("B♭", "B♭6", 74)
  val B6:  oldNote = oldNote("B", "B6", 75)

  val C7:  oldNote = oldNote("C", "C7", 76)
  val Cs7: oldNote = oldNote("C♯", "C♯7", 77)
  val Db7: oldNote = oldNote("D♭", "D♭7", 77)
  val D7:  oldNote = oldNote("D", "D7", 78)
  val Ds7: oldNote = oldNote("D♯", "D♯7", 79)
  val Eb7: oldNote = oldNote("E♭", "E♭7", 79)
  val E7:  oldNote = oldNote("E", "E7", 80)
  val F7:  oldNote = oldNote("F", "F7", 81)
  val Fs7: oldNote = oldNote("F♯", "F♯7", 82)
  val Gb7: oldNote = oldNote("G♭", "G♭7", 82)
  val G7:  oldNote = oldNote("G", "G7", 83)
  val Gs7: oldNote = oldNote("G♯", "G♯7", 84)
  val Ab7: oldNote = oldNote("A♭", "A♭7", 84)
  val A7:  oldNote = oldNote("A", "A7", 85)
  val As7: oldNote = oldNote("A♯", "A♯7", 86)
  val Bb7: oldNote = oldNote("B♭", "B♭7", 86)
  val B7:  oldNote = oldNote("B", "B7", 87)

  val C8:  oldNote = oldNote("C", "C8", 88)
}

